/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing;

import com.sun.org.apache.xpath.internal.XPathAPI;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JLabel;

/**
 *
 * @author alumno
 */
public class MostrarDepartamentos extends javax.swing.JFrame {

    private AccesoJDBC jdbc;
    private ResultSet rs;
    private int nRows;
    /**
     * Creates new form MostrarDepartamentos
     */
    public MostrarDepartamentos() {
        initComponents();
        jdbc = new AccesoJDBC();
        rs = jdbc.mosDept();
        if (rs == null){
            nRows = 0;
            this.l_posicion.setText("0 de "+nRows);
            this.primero.setEnabled(false);
            this.ultimo.setEnabled(false);
            this.anterior.setEnabled(false);
            this.siguiente.setEnabled(false);
            this.d_dept_no.setText("Sin Datos");
            this.d_dnombre.setText("Sin Datos");
            this.d_loc.setText("Sin Datos");
        } else {
            this.primero.setEnabled(false);
            this.anterior.setEnabled(false);
            try{
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnas = rsmd.getColumnCount();
                JLabel[] etiquetas = new JLabel[columnas];
                etiquetas[0] = this.l_1;
                etiquetas[1] = this.l_2;
                etiquetas[2] = this.l_3;
                for (int i = 0; i < columnas; i++){
                    etiquetas[i].setText(rsmd.getColumnName(i+1));
                }
                rs.last();
                nRows = rs.getRow();
                rs.first();
                mostrarRegistro();
            } catch (Exception e){
                e.printStackTrace();
            }
        }
    }
    
    private void mostrarRegistro(){
        try{
            this.l_posicion.setText(rs.getRow()+" de "+nRows);
            this.d_dept_no.setText(rs.getString("dept_no"));
            this.d_dnombre.setText(rs.getString("dnombre"));
            this.d_loc.setText(rs.getString("loc"));
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_1 = new javax.swing.JLabel();
        l_2 = new javax.swing.JLabel();
        l_3 = new javax.swing.JLabel();
        d_dept_no = new javax.swing.JTextField();
        d_dnombre = new javax.swing.JTextField();
        d_loc = new javax.swing.JTextField();
        primero = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        l_posicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_Titulo.setText("Departamentos");

        l_1.setText("1");

        l_2.setText("2");

        l_3.setText("3");

        d_dept_no.setEditable(false);

        d_dnombre.setEditable(false);

        d_loc.setEditable(false);

        primero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        primero.setText("|<");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        anterior.setText("<");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        siguiente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        siguiente.setText(">");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        ultimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ultimo.setText(">|");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(primero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ultimo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(l_Titulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_posicion))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(l_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(d_dept_no, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(d_dnombre)
                                .addComponent(d_loc))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_Titulo)
                    .addComponent(l_posicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_1)
                    .addComponent(d_dept_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_2)
                    .addComponent(d_dnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_3)
                    .addComponent(d_loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primero)
                    .addComponent(anterior)
                    .addComponent(siguiente)
                    .addComponent(ultimo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        try{
            if (rs.isLast()){
                this.ultimo.setEnabled(true);
                this.siguiente.setEnabled(true);
            }
            rs.first();
            this.primero.setEnabled(false);
            this.anterior.setEnabled(false);
            mostrarRegistro();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_primeroActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
       try{
            if (rs.isFirst()){
                this.primero.setEnabled(true);
                this.anterior.setEnabled(true);
            }
            rs.last();
            this.ultimo.setEnabled(false);
            this.siguiente.setEnabled(false);
            mostrarRegistro();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        try{
            if (rs.isLast()){
                this.ultimo.setEnabled(true);
                this.siguiente.setEnabled(true);
            }
            rs.previous();
            if (rs.isFirst()){
                this.primero.setEnabled(false);
                this.anterior.setEnabled(false);    
            }
            mostrarRegistro();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        try{
            if (rs.isFirst()){
                this.primero.setEnabled(true);
                this.anterior.setEnabled(true);
            }
            rs.next();
            if (rs.isLast()){
                this.ultimo.setEnabled(false);
                this.siguiente.setEnabled(false);    
            }
            mostrarRegistro();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarDepartamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JTextField d_dept_no;
    private javax.swing.JTextField d_dnombre;
    private javax.swing.JTextField d_loc;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_1;
    private javax.swing.JLabel l_2;
    private javax.swing.JLabel l_3;
    private javax.swing.JLabel l_Titulo;
    private javax.swing.JLabel l_posicion;
    private javax.swing.JButton primero;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
